### ISSUE TITLE
Meteor 1.0.0

### ISSUE THREAD

**Issue by clampr** [meteostat/routines#16]
Things got a bit messy when I transferred the legacy import routines to Python. It probably makes sense to refactor some of the code. I also propose a new name for this repository and the underlying Python Package: _Meteor_. Meteor will be the Meteostat-internal solution for collecting, managing and serving meteorological data.

## Roadmap

- [ ] Create a `next` branch
- [ ] Re-implement the core library
- [ ] Re-implement the routines and tasks
- [ ] Write tests
- [ ] Publish v1.0.0 release

## Concept

The repository will consist of a core library which handles the communication with the database and takes care of the corresponding schemas. Apart from the core it will also include scheduled tasks for importing and exporting data + utilities for performing tasks on-demand.

### Package Structure

- `/`
  - `core`
  - `cron`
    - `import`
    - `export`
    - `tasks`
  - `utils`
  - `sql`
    - `meteostat`
    - `system`

### Core Library: _Meteor_

- `meteor.Meteor(ctx, dev=False)`
  - `storage(key, value=None)`: Key-value storage for context-specific variables
  - `import(table, df)`: Import a DataFrame into a DB table
  - `query(sql)`: Run custom SQL query
  - `log(message)`: Create a log entry in the system DB
  - `error(message)`: Create an error in the system DB & inform DL (maybe daily)
  - `db`: The Meteostat DB connection
  - `_sys_db`: The system DB
  - `_config`: The config data

**This concept is work-in-progress. Feel free to share your ideas or take part in the development!**
